var annotated_dup =
[
    [ "Athlete", "class_athlete.html", "class_athlete" ],
    [ "Competition", "class_competition.html", "class_competition" ],
    [ "Date", "class_date.html", "class_date" ],
    [ "Delegation", "class_delegation.html", "class_delegation" ],
    [ "FileError", "class_file_error.html", "class_file_error" ],
    [ "FileStructureError", "class_file_structure_error.html", "class_file_structure_error" ],
    [ "FullTeam", "class_full_team.html", "class_full_team" ],
    [ "IndividualSport", "class_individual_sport.html", "class_individual_sport" ],
    [ "Medal", "class_medal.html", "class_medal" ],
    [ "NoCompetitions", "class_no_competitions.html", "class_no_competitions" ],
    [ "NoMedals", "class_no_medals.html", "class_no_medals" ],
    [ "NoMembers", "class_no_members.html", "class_no_members" ],
    [ "NonExistentAthlete", "class_non_existent_athlete.html", "class_non_existent_athlete" ],
    [ "NonExistentCompetition", "class_non_existent_competition.html", "class_non_existent_competition" ],
    [ "NonExistentPerson", "class_non_existent_person.html", "class_non_existent_person" ],
    [ "NonExistentSport", "class_non_existent_sport.html", "class_non_existent_sport" ],
    [ "NonExistentStaff", "class_non_existent_staff.html", "class_non_existent_staff" ],
    [ "NonExistentTeam", "class_non_existent_team.html", "class_non_existent_team" ],
    [ "NonExistentTrial", "class_non_existent_trial.html", "class_non_existent_trial" ],
    [ "NoSports", "class_no_sports.html", "class_no_sports" ],
    [ "NotATeamSport", "class_not_a_team_sport.html", "class_not_a_team_sport" ],
    [ "NoTrials", "class_no_trials.html", "class_no_trials" ],
    [ "Participant", "class_participant.html", "class_participant" ],
    [ "Person", "class_person.html", "class_person" ],
    [ "PersonAlreadyExists", "class_person_already_exists.html", "class_person_already_exists" ],
    [ "Sport", "class_sport.html", "class_sport" ],
    [ "Staff", "class_staff.html", "class_staff" ],
    [ "Team", "class_team.html", "class_team" ],
    [ "TeamAlreadyExists", "class_team_already_exists.html", "class_team_already_exists" ],
    [ "TeamSport", "class_team_sport.html", "class_team_sport" ],
    [ "Trial", "class_trial.html", "class_trial" ]
];