var _delegation_8h =
[
    [ "staffHash", "structstaff_hash.html", "structstaff_hash" ],
    [ "Compare", "class_compare.html", "class_compare" ],
    [ "Delegation", "class_delegation.html", "class_delegation" ],
    [ "FileError", "class_file_error.html", "class_file_error" ],
    [ "FileStructureError", "class_file_structure_error.html", "class_file_structure_error" ],
    [ "NonExistentSport", "class_non_existent_sport.html", "class_non_existent_sport" ],
    [ "NoSports", "class_no_sports.html", "class_no_sports" ],
    [ "NonExistentCompetition", "class_non_existent_competition.html", "class_non_existent_competition" ],
    [ "NonExistentTrial", "class_non_existent_trial.html", "class_non_existent_trial" ],
    [ "NonExistentPerson", "class_non_existent_person.html", "class_non_existent_person" ],
    [ "NonExistentStaff", "class_non_existent_staff.html", "class_non_existent_staff" ],
    [ "NonExistentAthlete", "class_non_existent_athlete.html", "class_non_existent_athlete" ],
    [ "NonExistentTeam", "class_non_existent_team.html", "class_non_existent_team" ],
    [ "PersonAlreadyExists", "class_person_already_exists.html", "class_person_already_exists" ],
    [ "TeamAlreadyExists", "class_team_already_exists.html", "class_team_already_exists" ],
    [ "NoMembers", "class_no_members.html", "class_no_members" ],
    [ "NoCompetitions", "class_no_competitions.html", "class_no_competitions" ],
    [ "NoTrials", "class_no_trials.html", "class_no_trials" ],
    [ "NoMedals", "class_no_medals.html", "class_no_medals" ],
    [ "NotATeamSport", "class_not_a_team_sport.html", "class_not_a_team_sport" ],
    [ "FullTeam", "class_full_team.html", "class_full_team" ],
    [ "NoRecords", "class_no_records.html", "class_no_records" ],
    [ "NoMissingResults", "class_no_missing_results.html", "class_no_missing_results" ],
    [ "staffHtab", "_delegation_8h.html#a6722a465a74fee67f4d7927592a58eae", null ],
    [ "staffHtabcit", "_delegation_8h.html#a32f643c322d65be9a71f55133f5813ed", null ],
    [ "staffHtabit", "_delegation_8h.html#ad1206cba26cee54402293de0e3b4f073", null ]
];